apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-api
  name: my-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - image: gcr.io/sit323-23t1-peijin-he-23d5252/node-api:v1
        imagePullPolicy: IfNotPresent
        name: node-api-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
